# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0002_auto_20170314_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='long_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='order',
            name='short_title',
        ),
        migrations.AddField(
            model_name='order',
            name='eo_proc_no',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Executive order or Proclamation number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fr_date',
            field=models.DateField(verbose_name='Date Published in the Federal Register'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fr_doc_no',
            field=models.CharField(max_length=20, verbose_name='Federal Register Document Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fr_pdf_url',
            field=models.URLField(verbose_name='Federal Register PDF URL'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fr_pub',
            field=models.BooleanField(default='True', verbose_name='Published in Federal Register'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fr_url',
            field=models.URLField(verbose_name='Federal Register URL'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ucsb_url',
            field=models.URLField(verbose_name='American Presidency Project URL'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wh_url',
            field=models.URLField(verbose_name='White House URL'),
        ),
    ]
