# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0005_auto_20170314_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='president',
            field=models.ForeignKey(default=45, on_delete=django.db.models.deletion.CASCADE, to='whitehouse.President'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sign_date',
            field=models.DateField(null=True),
        ),
    ]
