# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0013_auto_20170319_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='president',
            name='potus_slug',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='potus slug for seo'),
        ),
    ]
