# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0016_auto_20170320_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='president',
            name='potus_slug',
            field=models.SlugField(default='', max_length=20, unique=True, verbose_name='potus slug for seo'),
        ),
    ]
