# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0020_auto_20170325_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedStories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_story_title', models.CharField(max_length=100)),
                ('related_story_url', models.URLField()),
            ],
            options={
                'verbose_name': 'story',
                'verbose_name_plural': 'stories',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='new_related_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='whitehouse.RelatedStories'),
        ),
    ]
