# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencies',
            options={'verbose_name': 'agency', 'verbose_name_plural': 'agencies'},
        ),
        migrations.AlterModelOptions(
            name='authorities',
            options={'verbose_name': 'authority', 'verbose_name_plural': 'authorities'},
        ),
        migrations.AlterModelOptions(
            name='stories',
            options={'verbose_name': 'story', 'verbose_name_plural': 'stories'},
        ),
        migrations.AlterField(
            model_name='president',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='president',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='president',
            name='party',
            field=models.CharField(max_length=20, verbose_name='party'),
        ),
        migrations.AlterField(
            model_name='president',
            name='potus_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='potus'),
        ),
    ]
