# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0007_auto_20170314_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whitehouse.Agencies'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='related_story',
        ),
        migrations.AddField(
            model_name='order',
            name='related_story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whitehouse.Stories'),
        ),
    ]
