# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0015_order_order_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='president',
            name='potus_slug',
            field=models.SlugField(default='trump', max_length=20, unique=True, verbose_name='potus slug for seo'),
            preserve_default=False,
        ),
    ]
