# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0021_auto_20170325_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_item', models.TextField(blank=True, null=True)),
                ('deadline_days', models.DurationField(blank=True, null=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Deadlines',
        ),
        migrations.AlterModelOptions(
            name='agencies',
            options={'ordering': ['agency_long'], 'verbose_name': 'agency', 'verbose_name_plural': 'agencies'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='new_related_story',
        ),
        migrations.AddField(
            model_name='stories',
            name='story_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='order',
            name='related_story',
        ),
        migrations.AddField(
            model_name='order',
            name='related_story',
            field=models.ManyToManyField(to='whitehouse.Stories'),
        ),
        migrations.DeleteModel(
            name='RelatedStories',
        ),
        migrations.AddField(
            model_name='deadline',
            name='deadline_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whitehouse.Order'),
        ),
    ]
