# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0025_auto_20170327_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_slug',
            field=models.SlugField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='order',
            name='related_story',
            field=models.ManyToManyField(blank=True, to='whitehouse.Stories'),
        ),
    ]
