# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0027_auto_20170417_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_slug',
            field=models.SlugField(default='', max_length=512),
        ),
    ]
