# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0029_auto_20170418_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='deadline_days',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deadline',
        ),
        migrations.AddField(
            model_name='deadline',
            name='followup_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deadline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whitehouse.Order'),
            preserve_default=False,
        ),
    ]
