# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0030_auto_20170418_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='deadline_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whitehouse.Order'),
        ),
    ]
