# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0031_auto_20170418_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_words',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='eo_proc_no',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='EO num'),
        ),
    ]
