# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0032_auto_20170419_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='posted_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stories',
            name='story_title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
