# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0033_auto_20170420_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='posted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
