# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0009_auto_20170314_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bud_impact_url',
            field=models.URLField(blank=True, null=True, verbose_name='OMB Budgetary Impact Statement URL'),
        ),
        migrations.AlterField(
            model_name='order',
            name='agency',
            field=models.ManyToManyField(to='whitehouse.Agencies'),
        ),
        migrations.AlterField(
            model_name='order',
            name='related_story',
            field=models.ManyToManyField(blank=True, to='whitehouse.Stories'),
        ),
    ]
