# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0010_auto_20170317_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-sign_date']},
        ),
    ]
