# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0012_auto_20170318_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='agency',
            field=models.ManyToManyField(blank=True, to='whitehouse.Agencies'),
        ),
    ]
