# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0014_president_potus_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_slug',
            field=models.SlugField(default='null'),
            preserve_default=False,
        ),
    ]
