# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0018_auto_20170320_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
