# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0019_auto_20170322_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_item', models.TextField(blank=True, null=True)),
                ('deadline_days', models.DurationField(blank=True, null=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-sign_date']},
        ),
        migrations.AddField(
            model_name='order',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='order',
            name='related_story',
        ),
        migrations.AddField(
            model_name='order',
            name='related_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='whitehouse.Stories'),
        ),
    ]
